#ifndef BMS_CAN_PROTOCOL_H
#define BMS_CAN_PROTOCOL_H

#include <stdint.h>

#define BMS_CAN_PROTOCOL_VERSION                 1U
#define BMS_CAN_FRAME_DLC                        8U

#define BMS_CAN_COMMAND_ID                   0x5E0U
#define BMS_CAN_BASE_ID                      0x600U
#define BMS_CAN_LAYOUT_RESPONSE_BASE_ID       0x6D0U
#define BMS_CAN_CONFIG_RESPONSE_ID            0x6E0U
#define BMS_CAN_SUMMARY_BASE_ID               0x6F0U

#define BMS_CAN_SUMMARY_MAX_FRAMES              16U
#define BMS_CAN_SUMMARY_MAX_SIGNALS               8U
#define BMS_CAN_SUMMARY_PERIOD_MS              5000U

typedef enum {
    BMS_CAN_CMD_READ_CONFIG = 0x01,
    BMS_CAN_CMD_READ_SLOT = 0x02,
    BMS_CAN_CMD_BEGIN = 0x10,
    BMS_CAN_CMD_SET_COUNT = 0x11,
    BMS_CAN_CMD_SET_SLOT = 0x12,
    BMS_CAN_CMD_VALIDATE = 0x13,
    BMS_CAN_CMD_COMMIT = 0x14,
    BMS_CAN_CMD_SAVE = 0x15,
    BMS_CAN_CMD_ABORT = 0x16
} bms_can_command_t;

typedef enum {
    BMS_CAN_STATUS_OK = 0,
    BMS_CAN_STATUS_BAD_VERSION,
    BMS_CAN_STATUS_BAD_OPCODE,
    BMS_CAN_STATUS_BAD_TRANSACTION,
    BMS_CAN_STATUS_BAD_VALUE,
    BMS_CAN_STATUS_NO_TRANSACTION,
    BMS_CAN_STATUS_PERSISTENCE_BLOCKED,
    BMS_CAN_STATUS_PERSISTENCE_ERROR
} bms_can_status_t;

/* Signal IDs occupy four bits in a slot descriptor. Zero terminates a slot. */
typedef enum {
    BMS_CAN_SIGNAL_NONE = 0,
    BMS_CAN_SIGNAL_FORMAT_VERSION = 1,
    BMS_CAN_SIGNAL_STATE = 2,
    BMS_CAN_SIGNAL_SOC_PERMILLE = 3,
    BMS_CAN_SIGNAL_PACK_VOLTAGE_100MV = 4,
    BMS_CAN_SIGNAL_PACK_CURRENT_100MA = 5,
    BMS_CAN_SIGNAL_MIN_CELL_MV = 6,
    BMS_CAN_SIGNAL_MAX_CELL_MV = 7,
    BMS_CAN_SIGNAL_MAX_TEMPERATURE_DC = 8,
    BMS_CAN_SIGNAL_ACTIVE_FAULTS_LOW16 = 9,
    BMS_CAN_SIGNAL_ACTIVE_FAULTS = 10,
    BMS_CAN_SIGNAL_LATCHED_FAULTS = 11,
    BMS_CAN_SIGNAL_OUTPUT_REQUESTS = 12,
    BMS_CAN_SIGNAL_VALID_CELL_COUNT = 13,
    BMS_CAN_SIGNAL_VALID_TEMPERATURE_COUNT = 14
} bms_can_signal_t;

#define BMS_CAN_SIGNAL_MAX BMS_CAN_SIGNAL_VALID_TEMPERATURE_COUNT

#define BMS_CAN_ID_IS_LAYOUT_RESPONSE(id) \
    ((id) >= BMS_CAN_LAYOUT_RESPONSE_BASE_ID && \
     (id) < (BMS_CAN_LAYOUT_RESPONSE_BASE_ID + BMS_CAN_SUMMARY_MAX_FRAMES))
#define BMS_CAN_ID_IS_SUMMARY(id) \
    ((id) >= BMS_CAN_SUMMARY_BASE_ID && \
     (id) < (BMS_CAN_SUMMARY_BASE_ID + BMS_CAN_SUMMARY_MAX_FRAMES))
#define BMS_CAN_ID_IS_TELEMETRY(id) \
    ((id) >= BMS_CAN_BASE_ID && (id) <= 0x6FFU)

#endif /* BMS_CAN_PROTOCOL_H */
